### ISSUE TITLE
cannot deserialize packet / failed to establish connection with the node

### ISSUE THREAD

**Issue by liv-io** [dcSpark/carp#199]
Hello,

I am unable to synchronize carp from scratch in the preprod network. The logs show the following error message:

```
2024-11-25T07:38:04.507880Z  INFO carp: Starting Carp
2024-11-25T07:38:04.507891Z  INFO carp: Execution plan /indexer/execution_plans/default.toml
2024-11-25T07:38:04.508025Z  INFO carp: Config file PathBuf { inner: "/var/local/carp/config/default.yml" }
2024-11-25T07:38:04.515319Z  INFO carp::genesis: Parsing genesis file...
2024-11-25T07:38:04.518102Z  INFO carp::genesis: Finished parsing genesis file after 2.774732ms
2024-11-25T07:38:04.518111Z  INFO carp::genesis: Inserting genesis data into database...
2024-11-25T07:38:04.518310Z  INFO carp::genesis: Starting sync based on genesis hash d4b8de7a11d929a323373cbab6c1a9bdc931beffff11db111cf9d57356ee1937
2024-11-25T07:38:04.521923Z  INFO carp::genesis: Finished inserting genesis data after 3.81098ms
2024-11-25T07:38:04.528942Z  INFO cardano_net: connected to 127.0.0.1:30000 (127.0.0.1)
2024-11-25T07:38:04.529187Z  INFO cardano_net::stream: [82, 2, 82, 0, 82, D, E]
2024-11-25T07:38:04.529237Z ERROR cardano_net::stream: cannot deserialize packet cardano_sdk::protocol::handshake::HandshakeNode->Refuse->field0->cardano_sdk::protocol::handshake::RefuseReason->VersionMismatch->field0->cardano_sdk::protocol::basic::Versions->cardano_sdk::protocol::basic::Version: Custom("unknown version : 13")
Error: Failed to establish connection with the node

Caused by:
    0: protocol error Handshake reply but got an error decoding cardano_sdk::protocol::handshake::HandshakeNode->Refuse->field0->cardano_sdk::protocol::handshake::RefuseReason->VersionMismatch->field0->cardano_sdk::protocol::basic::Versions->cardano_sdk::protocol::basic::Version: Custom("unknown version : 13")1: Handshake reply but got an error decoding cardano_sdk::protocol::handshake::HandshakeNode->Refuse->field0->cardano_sdk::protocol::handshake::RefuseReason->VersionMismatch->field0->cardano_sdk::protocol::basic::Versions->cardano_sdk::protocol::basic::Version: Custom("unknown version : 13")
* Connection to 'cardano-node' on address '127.0.0.1:30000' was successful.
* Connection to 'postgresql' on address '127.0.0.1:5432' was successful.
Applying all pending migrations
No pending migrations
```

Resynchronizing Carp from scratch, including completely dropping the PostgreSQL database, did not resolve the issue for me.

### Network

PreProd

### Specifications

The hardware specifications are:
- 4 cores
- 10 GB
- 4 NVMe drives in RAID-5

### Versions

The software versions are:
- Debian 12
- cardano-node 10.1.2
- postgresql 15.x
- carp 3.3.0

### Configuration

- `default.yml`

  ```
  source:
    type: cardano_net
    relay:
      - 127.0.0.1
      - 30000
  sink:
    type: cardano
    db:
      type: postgres
      database_url: postgresql://carp:carp@127.0.0.1:5432/carp
    network: preprod # preview / preprod / testnet
  start_block:
  ```

Please let me know if I need to provide further details about the setup.

Thank you for your help.

**Comment by ecioppettini** [comment]
This should be fixed when we merge https://github.com/dcSpark/carp/pull/187

Although if we are not going to merge that soon maybe we could port only the source-related changes from there to the main branch (which require updating dcspark core to the branch were we use pallas_network instead of cardano_net and updating some interfaces).

**Comment by Ishannaik** [comment]
> This should be fixed when we merge [#187](https://github.com/dcSpark/carp/pull/187)
> 
> Although if we are not going to merge that soon maybe we could port only the source-related changes from there to the main branch (which require updating dcspark core to the branch were we use pallas_network instead of cardano_net and updating some interfaces).

  @ecioppettini Thanks for the update. I'm experiencing the same issue with mainnet using cardano-node 10.2.1 (protocol version 13).

  I tried building from the custom-networks branch hoping it might include the protocol v13 support, but I'm still getting the same error:

```
  ERROR cardano_net::stream: cannot deserialize packet 
  Custom("unknown version : 13")
```
  A few questions:
  1. Does PR #187 specifically add support for protocol version 13?
  2. Is there a timeline for merging #187?
  3. In the meantime, would it be possible to cherry-pick just the protocol version support changes to a hotfix branch? Many of us are stuck unable to use Carp with newer cardano-node versions.

I'd be happy to test any branch with protocol v13 support. Currently, the only alternative seems to be downgrading cardano-node, which isn't ideal for production environments.
